package com.spm.ParkMe.enums;

public enum CategoryNotification {
	DRIVER_ABUSIVE_PARKING,
	VIGILANT_ABUSIVE_PARKING,
	HANDICAP_REQUEST,
	DRIVER_EXPIRING_TICKET,
	VIGILANT_EXPIRING_TICKET,
	DRIVER_REFUNDED_TICKET,
	VIGILANT_ABUSIVE_PERSONAL_PARKINGLOT,
	DRIVER_ABUSIVE_PERSONAL_PARKINGLOT
}
